### PR TITLE
added a few small changes, i.e. allowing parfor in estimation, overwr…

### PR DESCRIPTION
**Pull request by SRSteinkamp**
Just a few quality of life changes:

* precompute can now overwrite
* true parameters also returns un-transformed parameters and sorts them to be in same order as latent parameters
* cpm_estimate has now a parfor flag
* I think the hemodynamic priors should be at 0 - but not sure

### CODE REVIEW

**Comment by iChaker** [comment]
Hello Simon,

Approved, thanks for keeping the repo up to date

Best
Iyadh

**Comment by SRSteinkamp** [comment]
For now I'll be working on a fork of the repo, as I wrote a bunch more functions for  diagnostics, visualizations, generating data etc. 

The functions are not in a great state so far, so it will be while till I open a pull request.

**Comment by iChaker** [comment]
Hey Simon,

Make sure to make incremental commits to keep things organized

**Comment by iChaker** [comment]
Also, how is the Alpha Tau situation going? Sorry I got a bit too lazy to
handle it :x

**Comment by SRSteinkamp** [comment]
Afaik we are staying in tau space for now, makes a few things easier (I hope^^).

I am afraid it will get messy at some point, cause I might remove functions that I am working on right now at a later state...

**Pull request merged**
